### ISSUE TITLE
ビルド方法や実行方法のドキュメント

### ISSUE THREAD

**Issue by yasuohayashibara** [NaokiTakahashi12/OpenHumanoidController#1]
ビルド方法や実行方法のドキュメントが無いので，追加する．

**Comment by NaokiTakahashi12** [comment]
ビルド方法の対応しました。https://github.com/NaokiTakahashi12/hc-early/commit/5846750d84f38e66e39e10f6c11bdf8788bb682c

**Comment by NaokiTakahashi12** [comment]
実行方法の対応しました。https://github.com/NaokiTakahashi12/hc-early/commit/b96a28ffbcd8b34b7ca8c8ee0593557b9166eec9

**Comment by NaokiTakahashi12** [comment]
現在時点でのソースコードの[Doxygen](https://naokitakahashi12.github.io/hc-early/)をオンライン上で確認できるようにしました。

**Comment by NaokiTakahashi12** [comment]
@yasuohayashibara 問題ないようであればクローズお願いします。

**Comment by yasuohayashibara** [comment]
issueをクローズします．
