### ISSUE TITLE
GankenKun歩行のための開発項目

### ISSUE THREAD

**Issue by yasuohayashibara** [NaokiTakahashi12/OpenHumanoidController#12]
GankenKun歩行のために残りの開発項目をリストアップする．

以下は行った．

- [x] KInematics
- [x] B3Mの制御（単体）

**Comment by NaokiTakahashi12** [comment]
Kinematicsは動作しないため修正お願いします
```
malloc: *** set a breakpoint in malloc_error_break to debug
```

**Comment by yasuohayashibara** [comment]
#7 において，RS485の信号を出力する直前までは確認できたので，issueを閉じます．
実際にH/Wで動作するかは別のissueとします．
