### ISSUE TITLE
IKが収束しない

### ISSUE THREAD

**Issue by yasuohayashibara** [NaokiTakahashi12/OpenHumanoidController#13]
IKの計算が収束しないことへの対処

**Comment by yasuohayashibara** [comment]
@NaokiTakahashi12 
別の要因かもしれませんが，GankenKunでは以下のようにしています．

https://github.com/NaokiTakahashi12/hc-early/blob/c17ebc6ff720e6bae913185f421626dbfb4c5201/src/Kinematics/Launcher.cpp#L173-L176

**Comment by NaokiTakahashi12** [comment]
https://github.com/NaokiTakahashi12/hc-early/commit/975a5e50586e8183dcd09911851489d810c35080
こちらで作業しています
現状としては，脚の伸縮運動は問題なく収束するのですが，歩行パターンを読み込む際に収束しないという状態です

**Comment by yasuohayashibara** [comment]
こちらおそらく解決したと思いますので，issueを閉じます．
