### ISSUE TITLE
Rigid Body Dynamic LibraryのInverse Kinematicsの精度の検証

### ISSUE THREAD

**Issue by yasuohayashibara** [NaokiTakahashi12/OpenHumanoidController#2]
Rigid Body Dynamic LibraryのInverse Kinematicsの精度を検証する．

Rigid Body Dynamic Library
https://rbdl.bitbucket.io

Inverse Kinematics
https://rbdl.bitbucket.io/de/d92/group__kinematics__group.html#gaa5eabd37ff8b0925d2ecbf49fee1a8a7

**Comment by yasuohayashibara** [comment]
安定バージョンのzipファイルをダウンロード
version 2.6.0

解凍して
```
cmake .
ccmake .
```
`RBDL_BUILD_ADDON_URDFREADER`を`ON`にする。

```
make
sudo make install
```

**Comment by yasuohayashibara** [comment]
解凍した以下のディレクトリにURDFを読み込むサンプルプログラムがあるため、それを別フォルダにコピー
/rbdl/examples/urdfreader

`example_urdfreader.cc`を以下のチェックプログラムに入れ替える。
チェック用プログラム
[example_urdfreader.txt](https://github.com/NaokiTakahashi12/hc-early/files/3537992/example_urdfreader.txt)
```
cmake .
make
```
以下をコピーして、`./example_urdfreader`を実行
https://github.com/NaokiTakahashi12/hc-early/blob/develop/data/urdf/DARwInOP.urdf

**Comment by yasuohayashibara** [comment]
脚を伸ばした状態(-0.005, 0.037, -0.308)から
x: -0.1 ~ 0.1 0.005 step
y: -0.1 ~ 0.1 0.005 step
z: 0.0 ~ 0.1 0.005 step
で検証

32000回の計算を行うのに４秒
0.13ms (Core i7)

誤差
x: -0.0022 ~ 0.0020
y: -0.0021 ~ 0.0020
z: -0.0043 ~ 0.0000

特異姿勢の近くが誤差が大きい．

**Comment by yasuohayashibara** [comment]
`accelite.urdf`でも行ったが，特異姿勢に近づかないせいか全て誤差は1mm以下となっている．
図示した結果，関節がずれているように見える．
さらなる検証が必要である．

**Comment by yasuohayashibara** [comment]
accelite.urdfを再生した結果
```
roslaunch urdf_tutorial display.launch model:=Accelite.urdf
```
形状データへのリンク`<geometry>`を削除して実行

https://youtu.be/gTQlYZaM_nQ

シリアルリンクの挙動であり，パラレルリンクの動きとは異なる．

**Comment by yasuohayashibara** [comment]
URDFに`<mimic>`というタグがあり，対応していればパラレルリンクが表現できるかもしれない．

また，AddLoopConstraintを使用することで，パラレルリンクも表現できるかもしれない．

https://rbdl.bitbucket.io/d7/de7/struct_rigid_body_dynamics_1_1_constraint_set.html#a68cf418a61f5922912a54723d17b22b6

**Comment by yasuohayashibara** [comment]
OPRVer1.urdfを表示させたところ平行リンクの挙動が見られた
```
roslaunch urdf_tutorial display.launch model:=OPRVer1.urdf
```

動画
https://youtu.be/_DPvDtg18mE

URDFを見ると上記で議論したmimicが使用されている。
```
  <gazebo>
    <plugin filename="libroboticsgroup_gazebo_mimic_joint_plugin.so" name="left_waist_front_pitch_mimic_joint_plugin">
      <joint>left_waist_pitch_joint</joint>
      <mimicJoint>left_waist_front_pitch_joint</mimicJoint>
      <hasPID/>
      <multiplier>-1</multiplier>
      <offset>0</offset>
      <sensitiveness>0.0</sensitiveness>
      <maxEffort>10.0</maxEffort>
    </plugin>
  </gazebo>
```

**Comment by yasuohayashibara** [comment]
上に示した逆運動学を求めるプログラムでOPRVer1.urdfを計算したところ、値の変動が見られなかった。
足先の位置は計算前も計算後も変動することなく、エラーも出力されない。
足先位置の計算は正常に行えているため、逆運動学の関数がOPRVer1.urdfで記述された平行リンクの形式の計算をサポートしていないおそれがあると考えられる。

**Comment by yasuohayashibara** [comment]
変動している様子が見られしたが，計算結果が正しくありません．
状況としては，膝下の計算は正しい答えを出していそうですが，膝上の計算が間違っています．
モデルを変更すると改善される可能性があるので，現在調査中です．

**Comment by NaokiTakahashi12** [comment]
> 変動している様子が見られしたが，計算結果が正しくありません．
> 状況としては，膝下の計算は正しい答えを出していそうですが，膝上の計算が間違っています．
> モデルを変更すると改善される可能性があるので，現在調査中です．

胴体から膝、膝から足先のように段階的に逆運動学を計算するのはいかがでしょうか？

**Comment by yasuohayashibara** [comment]
正しい答えが得られているという認識が間違っていたようです．
やはり正しく計算されていませんでした．

以下，30mm足先を上げたときの結果ですが，足先の位置は30mm上に移動していますが，関節の位置が正しくない位置にあります．角度も出力してみましたが，腿と膝の角度が異なっています．
（正しい場合は角度が一致する．）

![image](https://user-images.githubusercontent.com/5755200/64076948-45705b80-cd06-11e9-8bce-3e581dbc66d4.png)

URDFチェックのため，ピッチ関節だけ動かす動画を作成しました．
前回とほぼ同様ですが，平行リンクの動きをしています．

https://youtu.be/6LL192rM0fU

**Comment by NaokiTakahashi12** [comment]
逆運動学自体の計算が正常に終了している状態で考えられるのは
+ 入力しているベクトルが誤っている
+ ヤコビアンが計算できない
+ ボディの座標系に問題がある

アルゴリズム上の問題か見分けるために、RBDLのloggingをtrueにすることを提案します。

**Comment by yasuohayashibara** [comment]
調査します．

**Comment by yasuohayashibara** [comment]
最もシンプルな平行リンクを作成
こちらで検証する．

```
<?xml version="1.0" encoding="utf-8"?>
<robot name="parallel" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <material name="white">
    <color rgba="1.0 1.0 1.0 1.0"/>
  </material>
  <!-- import empty link -->
  <link name="base_link"/>
  <!-- joints -->
  <joint name="base_joint" type="fixed">
    <parent link="base_link"/>
    <child link="bottom_link"/>
    <origin rpy="0 0 0" xyz="0 0 0"/>
  </joint>
  <joint name="bottom_right_joint" type="revolute">
    <parent link="bottom_link"/>
    <child link="right_link"/>
    <origin rpy="0 0 0" xyz="1 0 0"/>
    <mimic joint="top_right_joint" multiplier="-1" offset="0"/>
    <limit effort="7" lower="-1.57" upper="1.57" velocity="4.0"/>
    <axis xyz="0 1 0"/>
  </joint>
  <joint name="top_right_joint" type="revolute">
    <parent link="right_link"/>
    <child link="top_link"/>
    <origin rpy="0 0 0" xyz="0 0 1"/>
    <limit effort="7" lower="-1.57" upper="1.57" velocity="4.0"/>
    <axis xyz="0 1 0"/>
  </joint>
  <joint name="top_left_joint" type="revolute">
    <parent link="top_link"/>
    <child link="left_link"/>
    <origin rpy="0 0 0" xyz="-1 0 0"/>
    <mimic joint="top_right_joint" multiplier="-1" offset="0"/>
    <limit effort="7" lower="-1.57" upper="1.57" velocity="4.0"/>
    <axis xyz="0 1 0"/>
  </joint>
  <!-- links -->
  <link name="bottom_link"/>
  <link name="right_link"/>
  <link name="left_link"/>
  <link name="top_link"/>
</robot>
```

動画
https://youtu.be/5cNnHtN8MnU

**Comment by yasuohayashibara** [comment]
RBDLの逆運動学の計算ではシリアルリンクとして計算されることを確認
dockerの環境でも同じ結果となる．

**Comment by NaokiTakahashi12** [comment]
> RBDLの逆運動学の計算ではシリアルリンクとして計算されることを確認
> dockerの環境でも同じ結果となる．

入力した情報を教えてください。

**Comment by yasuohayashibara** [comment]
使用したプログラムを以下に貼ります．
[check_ik.txt](https://github.com/NaokiTakahashi12/hc-early/files/3571883/check_ik.txt)

1mのリンクで平行リンクを構成して，初期姿勢で(0, 0, 1.0)にあるリンクを(0, 0, 1.2)に移動するように逆運動学を計算しました．
https://youtu.be/5cNnHtN8MnU

範囲外ですので，平行リンクとすると解無しとなる領域です．

結果は以下の通りです．
```
 -0.0202473　←　リンク１の角度（初期は０）
   0.221814　←　リンク２の角度（初期は０）
1.93344e-17　←　リンク３の角度（初期は０）
# x y z　←　初期の位置
0 0 0
1 0 0
1 0 1
0 0 1　←　逆運動学の計算に用いた位置
# x y z (result of calculating ik)　←　計算後の位置
0 0 0
1 0 0
0.979754 0 0.999795
5.66214e-15 0 1.2　←　目標位置(0, 0, 1.2)に近い位置になっている．
# orientation (result of calculating ik)　←　計算後のリンクの姿勢
 0.979754         0 -0.200205
        0         1         0
 0.200205         0  0.979754　←　本来は傾かないので単位行列になる．
```

**Comment by yasuohayashibara** [comment]
ドキュメントには以下の記述があるので，もう少し調査してみます．

`constraints for contact and collision handling, and closed loop mode`
https://rbdl.bitbucket.io/

**Comment by yasuohayashibara** [comment]
以下のような記述がありました．
どうもclosed loopはConstraintを使用した動力学の計算ではサポートしているが，逆運動学の計算ではサポートされていなさそうです．
念のため，AddLoopConstraint()を付け足して逆運動学の計算をしてみましたが，結果に変化はありませんでした．
指定するリンクやその他のパラメータを10種類ぐらい変更して実行しています．
（試行錯誤で作成していたプログラムは上書きして消してしまいました．．．）

https://rbdl.bitbucket.io/index.html

Added support for closed-loop models by replacing Contacts API by a new Constraints API. Loop constraints can be stabilized using Baumgarte stabilization. Special thanks to Davide Corradi for this contribution!

一応逆運動学のソースコードもざっと読んでみましたが，平行リンクの解を得る方法は見つけられていない状況です．

**Comment by NaokiTakahashi12** [comment]
平行リンクは別途の実装とする
