### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by yasuohayashibara** [NaokiTakahashi12/OpenHumanoidController#3]
以下をコメントアウトしないとerrorになります．

https://github.com/NaokiTakahashi12/hc-early/blob/82083c7af79316bbf4e03677606dc7f6c83db7b9/src/Tools/main.cpp#L81-L82

**Comment by yasuohayashibara** [comment]
環境設定の不足だと思いますが，Kinematicsをビルドすると以下のエラーになります．

```
SpatialPoint.cpp:14:10: fatal error: unsupported/Eigen/EulerAngles: そのようなファイルやディレクトリはありません
 #include <unsupported/Eigen/EulerAngles>
```

**Comment by NaokiTakahashi12** [comment]
報告ありがとうございます
原因究明いたします

**Comment by NaokiTakahashi12** [comment]
こちらで確認しましたが，問題の再現を行うことができませんでした
検証環境は以下になります

| OS | Eigen Version |
:--: | :--:
| Ubuntu 18.04 | 3.3.7 |
| Ubuntu 16.04 | 3.3.7 |
| Ubuntu 14.04 | 3.3.7 |

インストールに使用したものは以下になります
https://github.com/NaokiTakahashi12/hc-early/blob/82083c7af79316bbf4e03677606dc7f6c83db7b9/scripts/setup_require_package/build_and_install_eigen3.3.7.bash#L1-L15

考えられる要因として``` $EIGEN_INCLUDE_DIR ```を優先としてCMakeが探索するため，過去のEigenをincludeしている可能性があります
なお，現在の設定として必要としているShell環境変数としては，RBDLのみになっています

**Comment by yasuohayashibara** [comment]
`scripts/setup_require_package/build_and_install_eigen3.3.7.bash`を実行することで，ビルドできるようになりました．
Ubuntu1604だとaptでインストールされるのが`libzip4`ですので，そちらに変更して環境を設定しました．

**Comment by NaokiTakahashi12** [comment]
インストール対象ごとに切り替わるように追加で記述したいと思います

**Comment by yasuohayashibara** [comment]
こちら情報共有が目的で，共有できたためissueを閉じます．
必要に応じて再オープンしてください．
