### ISSUE TITLE
MultipleFKSelectorに関するドキュメント

### ISSUE THREAD

**Issue by yasuohayashibara** [NaokiTakahashi12/OpenHumanoidController#5]
MultipleFKSelectorの仕組みを理解するのに時間がかかった．
アルゴリズムの追加に関しては，どこかにドキュメントがあったほうが良いかもしれない．

https://github.com/NaokiTakahashi12/hc-early/blob/develop/src/Kinematics/ForwardProblemSolvers/MultipleFKSelector.cpp

**Comment by NaokiTakahashi12** [comment]
了解しました

**Comment by yasuohayashibara** [comment]
情報を共有したので，issueを閉じます．
必要に応じて再オープンしてください．
