### ISSUE TITLE
B3Mと正常に通信できないため調査する

### ISSUE THREAD

**Issue by yasuohayashibara** [NaokiTakahashi12/OpenHumanoidController#8]
B3Mが正常に通信できないため調査する．

**Comment by yasuohayashibara** [comment]
B3Mが正常に通信できないため調査する．

**Comment by yasuohayashibara** [comment]
以下の行の下にprintfを追加したら，リターンパケットが届くようになった．
理由は調査中
↑　勘違いでした．どこが要因か調査中

https://github.com/NaokiTakahashi12/hc-early/blob/78a94a0ee5f812e018843111d3ae40e8afc148fc/src/IO/Communicator/SerialFlowScheduleBase.cpp#L211

**Comment by yasuohayashibara** [comment]
以下エラーとなります．
printfを随所に入れたので，それが原因かもしれません．

```
{"Time":"2019-12-06 14:01:31.023691","Exe":"./binary/IO.out","Level":"Debug","Message":"ID1: 10 " }
SEND: 0x09 0x04 0x00 0x01 0x64 0x00 0x2a 0x01 0xffffff9d 

terminate called after throwing an instance of 'std::length_error'
  what():  deque::_M_new_elements_at_back
```

**Comment by yasuohayashibara** [comment]
連続して通信できています．

https://youtu.be/ff_qOJS_zdY

しかし上記のように，途中でエラーで停止します．
タイミングはまちまちですが，長い時には１分ぐらい通信できています．

**Comment by NaokiTakahashi12** [comment]
送り待ちパケットがオーバーフローして止まっているように思われます
調査し解決します

**Comment by yasuohayashibara** [comment]
上記の問題はあるかもしれませんが，通信は正常に機能していることが判明しましたので，issueを閉じます．
